import type { Scenario } from './types';

/** Kịch bản hội thoại nhập vai có mục tiêu (0 token — seed tĩnh). */
export const SCENARIOS: Scenario[] = [
  {
    id: 'restaurant',
    emoji: '🍜',
    title: 'Gọi món ở nhà hàng',
    role: 'a friendly waiter at a casual restaurant',
    you: 'khách hàng',
    context: 'Bạn vừa ngồi vào bàn, người phục vụ tới chào.',
    goals: ['Hỏi món gợi ý', 'Gọi ít nhất một món', 'Hỏi xin hóa đơn'],
    opener: "Hi there! Welcome. Here's the menu — can I get you something to drink first?",
  },
  {
    id: 'hotel',
    emoji: '🏨',
    title: 'Nhận phòng khách sạn',
    role: 'a hotel receptionist',
    you: 'khách đặt phòng',
    context: 'Bạn tới khách sạn để nhận phòng đã đặt.',
    goals: ['Cho biết đã đặt phòng', 'Hỏi giờ ăn sáng', 'Hỏi mật khẩu Wi-Fi'],
    opener: 'Good afternoon! Welcome to the Grand Hotel. Do you have a reservation with us?',
  },
  {
    id: 'interview',
    emoji: '💼',
    title: 'Phỏng vấn xin việc',
    role: 'a hiring manager interviewing a candidate',
    you: 'ứng viên',
    context: 'Buổi phỏng vấn cho vị trí bạn ứng tuyển.',
    goals: ['Giới thiệu bản thân', 'Nói về một điểm mạnh', 'Đặt một câu hỏi về công việc'],
    opener: "Thanks for coming in. To start, could you tell me a little about yourself?",
  },
  {
    id: 'directions',
    emoji: '🗺️',
    title: 'Hỏi đường',
    role: 'a helpful local on the street',
    you: 'khách du lịch bị lạc',
    context: 'Bạn đang tìm đường tới ga tàu nhưng bị lạc.',
    goals: ['Hỏi đường tới ga tàu', 'Hỏi mất bao lâu', 'Cảm ơn'],
    opener: 'You look a bit lost — are you looking for somewhere?',
  },
  {
    id: 'coffee',
    emoji: '☕',
    title: 'Small talk với đồng nghiệp',
    role: 'a friendly coworker at the office coffee machine',
    you: 'đồng nghiệp',
    context: 'Bạn gặp đồng nghiệp ở khu pha cà phê buổi sáng.',
    goals: ['Chào và hỏi cuối tuần thế nào', 'Kể một việc bạn đã làm', 'Kết thúc lịch sự'],
    opener: 'Morning! Ugh, Mondays. How was your weekend?',
  },
  {
    id: 'doctor',
    emoji: '🩺',
    title: 'Đi khám bệnh',
    role: 'a doctor at a clinic',
    you: 'bệnh nhân',
    context: 'Bạn tới phòng khám vì thấy không khỏe.',
    goals: ['Mô tả triệu chứng', 'Trả lời từ khi nào', 'Hỏi cách điều trị'],
    opener: 'Hello, come on in. So, what seems to be the problem today?',
  },
  {
    id: 'shopping',
    emoji: '👕',
    title: 'Mua sắm quần áo',
    role: 'a shop assistant in a clothing store',
    you: 'khách mua hàng',
    context: 'Bạn đang tìm một chiếc áo khoác.',
    goals: ['Nói bạn tìm gì', 'Hỏi size khác / thử đồ', 'Hỏi giá'],
    opener: 'Hi! Let me know if you need any help finding something.',
  },
  {
    id: 'airport',
    emoji: '✈️',
    title: 'Làm thủ tục sân bay',
    role: 'an airline check-in agent',
    you: 'hành khách',
    context: 'Bạn làm thủ tục cho chuyến bay.',
    goals: ['Đưa thông tin chuyến bay', 'Gửi hành lý', 'Hỏi cổng ra máy bay'],
    opener: 'Good morning! May I see your passport and booking, please?',
  },
];
